### ISSUE TITLE
add more fonts 

### ISSUE THREAD

**Issue by zentoLu** [wentin/font-playground#1]
this project is very interesting , but i can't find proper font for our pages  ,i wanna to know how to add more fonts

**Comment by wentin** [comment]
@zentoLu thanks for the suggestions! Want to clarify your request, do you want to add fonts of your own? Do you want to add variable font or regular font?

**Comment by zentoLu** [comment]
yes , i found some font files in ttf , so i want to import it to this project

**Comment by wentin** [comment]
@zentoLu gotcha, this feature will be worked on! thanks for the suggestion.
